### ISSUE TITLE
Import error on python 3.8

### ISSUE THREAD

**Issue by matthiaskoenig** [biosustain/cameo#256]
I just tried importing a model in cameo, but get the following import error:
```
Traceback (most recent call last):
  File "/home/mkoenig/git/fbc_curation/fbc_curation/cameo_solver.py", line 19, in <module>
    from cameo import load_model
  File "/home/mkoenig/envs/fbc_curation/lib/python3.8/site-packages/cameo/__init__.py", line 97, in <module>
    from .flux_analysis.analysis import flux_variability_analysis, phenotypic_phase_plane
  File "/home/mkoenig/envs/fbc_curation/lib/python3.8/site-packages/cameo/flux_analysis/__init__.py", line 18, in <module>
    from .simulation import *
  File "/home/mkoenig/envs/fbc_curation/lib/python3.8/site-packages/cameo/flux_analysis/simulation.py", line 44, in <module>
    from cameo.visualization.palette import mapper, Palette
  File "/home/mkoenig/envs/fbc_curation/lib/python3.8/site-packages/cameo/visualization/__init__.py", line 17, in <module>
    from .visualization import *
  File "/home/mkoenig/envs/fbc_curation/lib/python3.8/site-packages/cameo/visualization/visualization.py", line 24, in <module>
    import networkx as nx
  File "/home/mkoenig/envs/fbc_curation/lib/python3.8/site-packages/networkx/__init__.py", line 76, in <module>
    import networkx.readwrite
  File "/home/mkoenig/envs/fbc_curation/lib/python3.8/site-packages/networkx/readwrite/__init__.py", line 14, in <module>
    from networkx.readwrite.gml import *
  File "/home/mkoenig/envs/fbc_curation/lib/python3.8/site-packages/networkx/readwrite/gml.py", line 39, in <module>
    from cgi import escape
ImportError: cannot import name 'escape' from 'cgi' (/usr/lib/python3.8/cgi.py)
```
There is probably no python 3.8 support yet ?.
In addition I do not see any python 3.7 and python 3.8 tests in continuous integration and your master branch is failing the tests (https://travis-ci.org/github/biosustain/cameo).

I did a clean install in a python 3.8 virtualenv. Just trying to load a model with
```
from cameo import load_model
model = load_model(model_path)
``` 
Best Matthias

**Comment by matthiaskoenig** [comment]
Works in python 3.7.

**Comment by Midnighter** [comment]
`load_model` is still on the list of things to move to cobrapy. With regard to support, I wouldn't expect anything to happen until @phantomas1234 is back to work in September.

**Comment by matthiaskoenig** [comment]
No problem. I just posted this to keep track of the issues. No urgent need to fix these. I have workarounds for what I wanted to try.
